#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Mouse actions for the block
case $BLOCK_BUTTON in
	1) pamixer -t ;;
	4) pamixer -i 3 ;;
	5) pamixer -d 3 ;;
esac

#Display volume
VOLUME=$(pamixer --get-volume)
[[ $(pamixer --get-mute) = "true" ]] && echo -n '<span color="#b4befe"> </span>' || [[ $VOLUME = 0 ]] && echo -n '<span color="#b4befe"> </span>' || [[ $VOLUME < 50 ]] && echo -n '<span color="#b4befe"> </span>' || echo -n '<span color="#b4befe"> </span>';
echo $VOLUME%;