#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Mouse actions for the block
case $BLOCK_BUTTON in
	1) pamixer -t ;;
	4) pamixer -i 3 ;;
	5) pamixer -d 3 ;;
esac

#Toggle mute
[[ $(pamixer --get-mute) = "true" ]] && echo -ne '<span color=\"#b4befe\">%</span>'&& exit
#Display volume
[[ $(pamixer --get-volume) = 0 ]] && echo -n ' ' || [[ $(pamixer --get-volume) < 50 ]] && echo -n ' ' echo -n '  ';
echo $(pamixer --get-volume)%